"""Initial tables

Revision ID: c806aa9d2391
Revises:
Create Date: 2025-02-16 20:13:49.560847

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c806aa9d2391"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parcel_types",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("name", sa.String(50), nullable=False),
    )
    op.create_table(
        "parcels",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("name", sa.String(100), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("type_id", sa.Integer(), sa.ForeignKey("parcel_types.id"), nullable=False),
        sa.Column("content_value_usd", sa.Float(), nullable=False),
        sa.Column("delivery_cost_rub", sa.Float(), nullable=True),
        sa.Column("session_id", sa.String(100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("parcels")
    op.drop_table("parcel_types")
    # ### end Alembic commands ###
